name: Deploy GitHub Pages - Aggiornamento sprint1
on:
  push:
    branches: [main]
    paths:
      - "ConwayLife/Sprint1/conway26Java/userDocs/conway26Java_v0.html"
      - "ConwayLife/Sprint2/conway26JavaSwing/userDocs/conway26JavaSwing_v0.html"
      - "conway26GuiHtml/userDocs/conway26GuiHtml_v0.html"
      - "docs/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copia il file nella root
        run: cp ConwayLife/Sprint1/conway26Java/userDocs/conway26Java_v0.html ./docs/conway26Java_v0.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
